ch_cookie_consent: 
  categories: ['analytics', 'tracking', 'social_media', 'marketing']
  theme: 'light' # light, dark
  use_logger: true # Logs user actions to database
  position: 'bottom' # top, bottom
  simplified: true # When set to true the user can only deny or accept all cookies at once
  http_only: true # Sets HttpOnly on cookies
  form_action: 'app_home' # When set, xhr-Requests will only be sent to this route. Take care of having the route available.
  csrf_protection: true # The cookie consent form is csrf protected or not
